AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'config/**/*'
    - 'config/puma*'
    - 'bin/*'
    - 'app/mailers/*'
    - 'db/**/*'
