development: &default
  adapter: mysql2
  encoding: utf8
  database: urllookup
  username: root
  password:
  port: 3306
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
test:
  <<: *default
  database: urllookup_test
production:
  <<: *default
  database: urllookup
