redis_dev:
  url: redis://localhost:6379
  hashcode: 0
redis_test1:
  url: redis://localhost:6379
  hashcode: 0
redis_test2:
  url: redis://localhost:6379
  hashcode: 1
redis_cluster1:
  url: redis://localhost:6379
  hashcode: 0
redis_cluster2:
  url: redis://localhost:6379
  hashcode: 1
redis_cluster3:
  url: redis://localhost:6379
  hashcode: 2
